title: NoTeX - Concept
theme: minima
minima:
  skin: dark
  
author: Luke J Andrews
email: l.j.andrews.uk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tex-like conceptual note taking tool
# social links
github_username: LukJA

show_excerpts: true # set to false to remove excerpts on the homepage
url: "https://lukja.github.io/" # the base hostname & protocol for your site
baseurl: "/NoTeX-Concept"